node:
  image: vibioh/node:latest
  command: node ${NODE_COMMAND}
  working_dir: /usr/src
  volumes:
  - ${WORKING_DIR}:/usr/src
  - ${NODE_GLOBAL_DIR}:/usr/node
  log_opt:
    max-size: '50m'
  tty: true
  privileged:true
  cpu_shares: 512
  mem_limit: 268435456
  expose:
  - ${NODE_PORT}/tcp

