node:
  image: registry.cn-hangzhou.aliyuncs.com/karelcc/mynode
  command: node ${NODE_COMMAND}
  working_dir: /usr/src
  volumes:
    - ${WORKING_DIR}:/usr/src
  log_opt:
    max-size: '50m'
  tty: true
  cpu_shares: 512
  mem_limit: 268435456
  labels:
    io.rancher.container.hostname_override: container_name