.catalog:
  name: NodeJS
  version: latest
  uuid: nodejs-0
  questions:
  - variable: WORKING_DIR
    description: 'Working directory path'
    label: 'Working dir:'
    required: true
    default: /var/www/eggjs
    type: string
  - variable: NODE_COMMAND
    description: 'Script to run at startup'
    label: 'Script path:'
    required: true
    default: index.js
    type: string
