.catalog:
  name: NodeJS
  version: latest
  uuid: nodejs-0
  questions:
  - variable: WORKING_DIR
    description: 'Working directory path'
    label: 'Working dir:'
    required: true
    default: /var/www/eggjs
    type: string
  - variable: NODE_COMMAND
    description: 'Script to run at startup'
    label: 'Script path:'
    required: true
    default: index.js
    type: string
  - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
  - variable: host_label
    label: "Host Label to MongoDB Tags"
    description: |
      Host label to use as MongoDB 'value' tag.
      Example: 'database'
    required: false
    type: "string"
  - variable: debug
    description: "Enable Debug log for Mongo containers"
    label: "Debug"
    type: "string"
    required: false
    default: ""
mongo-cluster:
  scale: 3
  retain_ip: true
  metadata:
    mongo:
      yml:
        replset.name: "${replset_name}"