.catalog:
  name: NodeJS
  version: latest
  uuid: nodejs-0
  questions:
  - variable: NODE_PORT
    description: 'Node port for eggjs'
    label: 'Node port:'
    required: true
    default: 7001
    type: int
  - variable: WORKING_DIR
    description: 'Working directory path'
    label: 'Working dir:'
    required: true
    default: /var/www/eggjs
    type: string
  - variable: NODE_COMMAND
    description: 'Script to run at startup'
    label: 'Script path:'
    required: true
    default: index.js
    type: string
  - variable: NODE_GLOBAL_DIR
    description: 'NPM global prefix directory'
    label: 'Npm directory:'
    required: true
    default: /var/node
    type: string
